services:
  authenticated-mosquitto:
    image: "eclipse-mosquitto:2.0.20"
    ports:
      - "1883:1883"
      - "8080:8080"
    volumes:
      - ./mosquitto-conf/auth:/mosquitto/config:ro
  unauthenticated-mosquitto:
    image: "eclipse-mosquitto:2.0.20"
    ports:
      - "18830:1883"
      - "8081:8080"
    volumes:
      - ./mosquitto-conf/unauth:/mosquitto/config:ro
